### PR TITLE
Pertf tests

### PR DESCRIPTION
**Pull request by Kerrigan29a**
I have added a test function to compare your ValidMoves function against the Perft Results obtained from https://www.chessprogramming.org/Perft_Results.

```bash
> go test
--- FAIL: TestPerfResults (0.04s)
    move_test.go:266: rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
    move_test.go:267:
         A B C D E F G H
        8♜ ♞ ♝ ♛ ♚ ♝ ♞ ♜
        7♟ ♟ ♟ ♟ ♟ ♟ ♟ ♟
        6- - - - - - - -
        5- - - - - - - -
        4- - - - - - - -
        3- - - - - - - -
        2♙ ♙ ♙ ♙ ♙ ♙ ♙ ♙
        1♖ ♘ ♗ ♕ ♔ ♗ ♘ ♖

    move_test.go:268: Depth: 3 Expected: 8902 Got: 8000
    move_test.go:266: r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1
    move_test.go:267:
         A B C D E F G H
        8♜ - - - ♚ - - ♜
        7♟ - ♟ ♟ ♛ ♟ ♝ -
        6♝ ♞ - - ♟ ♞ ♟ -
        5- - - ♙ ♘ - - -
        4- ♟ - - ♙ - - -
        3- - ♘ - - ♕ - ♟
        2♙ ♙ ♙ ♗ ♗ ♙ ♙ ♙
        1♖ - - - ♔ - - ♖

    move_test.go:268: Depth: 2 Expected: 2039 Got: 2304
    move_test.go:266: 8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - - 0 1
    move_test.go:267:
         A B C D E F G H
        8- - - - - - - -
        7- - ♟ - - - - -
        6- - - ♟ - - - -
        5♔ ♙ - - - - - ♜
        4- ♖ - - - ♟ - ♚
        3- - - - - - - -
        2- - - - ♙ - ♙ -
        1- - - - - - - -

    move_test.go:268: Depth: 2 Expected: 191 Got: 196
    move_test.go:266: 8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - - 0 1
    move_test.go:267:
         A B C D E F G H
        8- - - - - - - -
        7- - ♟ - - - - -
        6- - - ♟ - - - -
        5♔ ♙ - - - - - ♜
        4- ♖ - - - ♟ - ♚
        3- - - - - - - -
        2- - - - ♙ - ♙ -
        1- - - - - - - -

    move_test.go:268: Depth: 3 Expected: 2812 Got: 2744
    move_test.go:266: r3k2r/Pppp1ppp/1b3nbN/nP6/BBP1P3/q4N2/Pp1P2PP/R2Q1RK1 w kq - 0 1
    move_test.go:267:
         A B C D E F G H
        8♜ - - - ♚ - - ♜
        7♙ ♟ ♟ ♟ - ♟ ♟ ♟
        6- ♝ - - - ♞ ♝ ♘
        5♞ ♙ - - - - - -
        4♗ ♗ ♙ - ♙ - - -
        3♛ - - - - ♘ - -
        2♙ ♟ - ♙ - - ♙ ♙
        1♖ - - ♕ - ♖ ♔ -

    move_test.go:268: Depth: 2 Expected: 264 Got: 36
    move_test.go:266: r3k2r/Pppp1ppp/1b3nbN/nP6/BBP1P3/q4N2/Pp1P2PP/R2Q1RK1 w kq - 0 1
    move_test.go:267:
         A B C D E F G H
        8♜ - - - ♚ - - ♜
        7♙ ♟ ♟ ♟ - ♟ ♟ ♟
        6- ♝ - - - ♞ ♝ ♘
        5♞ ♙ - - - - - -
        4♗ ♗ ♙ - ♙ - - -
        3♛ - - - - ♘ - -
        2♙ ♟ - ♙ - - ♙ ♙
        1♖ - - ♕ - ♖ ♔ -

    move_test.go:268: Depth: 3 Expected: 9467 Got: 216
    move_test.go:266: r2q1rk1/pP1p2pp/Q4n2/bbp1p3/Np6/1B3NBn/pPPP1PPP/R3K2R b KQ - 0 1
    move_test.go:267:
         A B C D E F G H
        8♜ - - ♛ - ♜ ♚ -
        7♟ ♙ - ♟ - - ♟ ♟
        6♕ - - - - ♞ - -
        5♝ ♝ ♟ - ♟ - - -
        4♘ ♟ - - - - - -
        3- ♗ - - - ♘ ♗ ♞
        2♟ ♙ ♙ ♙ - ♙ ♙ ♙
        1♖ - - - ♔ - - ♖

    move_test.go:268: Depth: 2 Expected: 264 Got: 36
    move_test.go:266: r2q1rk1/pP1p2pp/Q4n2/bbp1p3/Np6/1B3NBn/pPPP1PPP/R3K2R b KQ - 0 1
    move_test.go:267:
         A B C D E F G H
        8♜ - - ♛ - ♜ ♚ -
        7♟ ♙ - ♟ - - ♟ ♟
        6♕ - - - - ♞ - -
        5♝ ♝ ♟ - ♟ - - -
        4♘ ♟ - - - - - -
        3- ♗ - - - ♘ ♗ ♞
        2♟ ♙ ♙ ♙ - ♙ ♙ ♙
        1♖ - - - ♔ - - ♖

    move_test.go:268: Depth: 3 Expected: 9467 Got: 216
    move_test.go:266: rnbq1k1r/pp1Pbppp/2p5/8/2B5/8/PPP1NnPP/RNBQK2R w KQ - 1 8
    move_test.go:267:
         A B C D E F G H
        8♜ ♞ ♝ ♛ - ♚ - ♜
        7♟ ♟ - ♙ ♝ ♟ ♟ ♟
        6- - ♟ - - - - -
        5- - - - - - - -
        4- - ♗ - - - - -
        3- - - - - - - -
        2♙ ♙ ♙ - ♘ ♞ ♙ ♙
        1♖ ♘ ♗ ♕ ♔ - - ♖

    move_test.go:268: Depth: 2 Expected: 1486 Got: 1936
    move_test.go:266: r4rk1/1pp1qppp/p1np1n2/2b1p1B1/2B1P1b1/P1NP1N2/1PP1QPPP/R4RK1 w - - 0 10
    move_test.go:267:
         A B C D E F G H
        8♜ - - - - ♜ ♚ -
        7- ♟ ♟ - ♛ ♟ ♟ ♟
        6♟ - ♞ ♟ - ♞ - -
        5- - ♝ - ♟ - ♗ -
        4- - ♗ - ♙ - ♝ -
        3♙ - ♘ ♙ - ♘ - -
        2- ♙ ♙ - ♕ ♙ ♙ ♙
        1♖ - - - - ♖ ♔ -

    move_test.go:268: Depth: 2 Expected: 2079 Got: 2116
FAIL
exit status 1
FAIL	github.com/Kerrigan29a/chess	0.285s
```

### CODE REVIEW

**Comment by andersfylling** [comment]
Nice! In addition to checking for incorrect moves, could you add time tracking? Such that it can "compare" against other move generators.

**Comment by captncraig** [comment]
Very cool. It seems there is definitely room for bug hunting. Could a `Divide` output be generated from this output to help narrow it down?

**Comment by Kerrigan29a** [comment]
@captncraig what do you want to see? A perft number for each children of the root node?

**Comment by andersfylling** [comment]
The technique is called "divide and conquer" and I believe it's described in detail on the chess programming website(?)

**Comment by notnil** [comment]
Wow this is awesome.  I did some optimization code which may be affecting the accuracy of results.  Will take a look.

**Comment by Kerrigan29a** [comment]
I have fixed an error in my code

The new test result is

```bash
> go test
--- FAIL: TestPerfResults (4.96s)
    move_test.go:265: rnbq1k1r/pp1Pbppp/2p5/8/2B5/8/PPP1NnPP/RNBQK2R w KQ - 1 8
    move_test.go:266:
         A B C D E F G H
        8♜ ♞ ♝ ♛ - ♚ - ♜
        7♟ ♟ - ♙ ♝ ♟ ♟ ♟
        6- - ♟ - - - - -
        5- - - - - - - -
        4- - ♗ - - - - -
        3- - - - - - - -
        2♙ ♙ ♙ - ♘ ♞ ♙ ♙
        1♖ ♘ ♗ ♕ ♔ - - ♖

    move_test.go:267: Depth: 3 Expected: 62379 Got: 62416
FAIL
exit status 1
FAIL	github.com/Kerrigan29a/chess	5.212s
```

**Comment by Kerrigan29a** [comment]
@captncraig I have added detailed information.

```bash
> go test
--- FAIL: TestPerfResults (3.73s)
    move_test.go:265: Depth: 3 Expected: 62379 Got: 62416
    move_test.go:266: ##############################
    move_test.go:267: # Original position info
    move_test.go:268: ###
    move_test.go:269: rnbq1k1r/pp1Pbppp/2p5/8/2B5/8/PPP1NnPP/RNBQK2R w KQ - 1 8
    move_test.go:270:
         A B C D E F G H
        8♜ ♞ ♝ ♛ - ♚ - ♜
        7♟ ♟ - ♙ ♝ ♟ ♟ ♟
        6- - ♟ - - - - -
        5- - - - - - - -
        4- - ♗ - - - - -
        3- - - - - - - -
        2♙ ♙ ♙ - ♘ ♞ ♙ ♙
        1♖ ♘ ♗ ♕ ♔ - - ♖

    move_test.go:271: ##############################
    move_test.go:272: # Details in JSONL (http://jsonlines.org)
    move_test.go:273: ###
    move_test.go:275: {"position": "rnbq2kr/pp1Pbppp/2p5/8/2B5/8/PPP1NnPP/RNBQ1K1R w - - 1 9", "moves": 43}
    move_test.go:275: {"position": "rnb2k1r/pp1Pbppp/2p5/q7/2B5/8/PPP1NnPP/RNBQ1K1R w - - 1 9", "moves": 46}
    move_test.go:275: {"position": "rnb2k1r/pp1Pbppp/1qp5/8/2B5/8/PPP1NnPP/RNBQ1K1R w - - 1 9", "moves": 46}
    move_test.go:275: {"position": "rnb2k1r/ppqPbppp/2p5/8/2B5/8/PPP1NnPP/RNBQ1K1R w - - 1 9", "moves": 47}
    move_test.go:275: {"position": "rnb2k1r/pp1qbppp/2p5/8/2B5/8/PPP1NnPP/RNBQ1K1R w - - 0 9", "moves": 40}
    move_test.go:275: {"position": "rnb1qk1r/pp1Pbppp/2p5/8/2B5/8/PPP1NnPP/RNBQ1K1R w - - 1 9", "moves": 51}
    move_test.go:275: {"position": "rnbq1kr1/pp1Pbppp/2p5/8/2B5/8/PPP1NnPP/RNBQ1K1R w - - 1 9", "moves": 43}
    move_test.go:275: {"position": "rnbq1k1r/pp1P1ppp/2p5/8/2B5/b7/PPP1NnPP/RNBQ1K1R w - - 1 9", "moves": 42}
    move_test.go:275: {"position": "rnbq1k1r/pp1P1ppp/2p5/8/1bB5/8/PPP1NnPP/RNBQ1K1R w - - 1 9", "moves": 41}
    move_test.go:275: {"position": "rnbq1k1r/pp1P1ppp/2p5/8/2B4b/8/PPP1NnPP/RNBQ1K1R w - - 1 9", "moves": 41}
    move_test.go:275: {"position": "rnbq1k1r/pp1P1ppp/2p5/2b5/2B5/8/PPP1NnPP/RNBQ1K1R w - - 1 9", "moves": 42}
    move_test.go:275: {"position": "rnbq1k1r/pp1P1ppp/2p5/6b1/2B5/8/PPP1NnPP/RNBQ1K1R w - - 1 9", "moves": 42}
    move_test.go:275: {"position": "rnbq1k1r/pp1P1ppp/2pb4/8/2B5/8/PPP1NnPP/RNBQ1K1R w - - 1 9", "moves": 43}
    move_test.go:275: {"position": "rnbq1k1r/pp1P1ppp/2p2b2/8/2B5/8/PPP1NnPP/RNBQ1K1R w - - 1 9", "moves": 43}
    move_test.go:275: {"position": "rn1q1k1r/pp1bbppp/2p5/8/2B5/8/PPP1NnPP/RNBQ1K1R w - - 0 9", "moves": 40}
    move_test.go:275: {"position": "rnbq1k1r/pp1Pbppp/2p5/8/2B5/8/PPP1N1PP/RNBn1K1R w - - 0 9", "moves": 36}
    move_test.go:275: {"position": "rnbq1k1r/pp1Pbppp/2p5/8/2B5/8/PPP1N1PP/RNBQ1K1n w - - 0 9", "moves": 41}
    move_test.go:275: {"position": "rnbq1k1r/pp1Pbppp/2p5/8/2B5/3n4/PPP1N1PP/RNBQ1K1R w - - 1 9", "moves": 39}
...
```

Each line is a [JSON Line](http://jsonlines.org). You can extract each line with the following command to call any other UCI compatible engine to compare
```bash
> go test | grep '"position"' | cut -d : -f 3- | jq .
{
  "position": "rnbq2kr/pp1Pbppp/2p5/8/2B5/8/PPP1NnPP/RNBQ1K1R w - - 1 9",
  "moves": 43
}
{
  "position": "rnb2k1r/pp1Pbppp/2p5/q7/2B5/8/PPP1NnPP/RNBQ1K1R w - - 1 9",
  "moves": 46
}
{
  "position": "rnb2k1r/pp1Pbppp/1qp5/8/2B5/8/PPP1NnPP/RNBQ1K1R w - - 1 9",
  "moves": 46
}
{
  "position": "rnb2k1r/ppqPbppp/2p5/8/2B5/8/PPP1NnPP/RNBQ1K1R w - - 1 9",
  "moves": 47
}
{
  "position": "rnb2k1r/pp1qbppp/2p5/8/2B5/8/PPP1NnPP/RNBQ1K1R w - - 0 9",
  "moves": 40
}
{
  "position": "rnb1qk1r/pp1Pbppp/2p5/8/2B5/8/PPP1NnPP/RNBQ1K1R w - - 1 9",
  "moves": 51
}
{
  "position": "rnbq1kr1/pp1Pbppp/2p5/8/2B5/8/PPP1NnPP/RNBQ1K1R w - - 1 9",
  "moves": 43
}
{
  "position": "rnbq1k1r/pp1P1ppp/2p5/8/2B5/b7/PPP1NnPP/RNBQ1K1R w - - 1 9",
  "moves": 42
}
{
  "position": "rnbq1k1r/pp1P1ppp/2p5/8/1bB5/8/PPP1NnPP/RNBQ1K1R w - - 1 9",
  "moves": 41
}
{
  "position": "rnbq1k1r/pp1P1ppp/2p5/8/2B4b/8/PPP1NnPP/RNBQ1K1R w - - 1 9",
  "moves": 41
}
```

**Comment by notnil** [comment]
It could be promotion.  How is that counted?

**Comment by captncraig** [comment]
This is great work. I took your code and got a little carried away with it. I made another repo at https://github.com/captncraig/perftwalk with my dedicated test harness. It runs perft, but also runs stockfish over uci, and compares results. It will recurse down paths with bad counts until it finds a bad or missed move. So it will always give a position and a failure for a test failure.

What it has found so far:

```
2018/12/14 00:53:57 Testing r3k2N/p1ppq1b1/1n2pnp1/1b1P4/1p2P3/2N2Q1p/PPPBBPPP/R3K2R b KQkq - 0 2
2018/12/14 00:53:57
 A B C D E F G H
8♜ - - - ♚ - - ♘
7♟ - ♟ ♟ ♛ - ♝ -
6- ♞ - - ♟ ♞ ♟ -
5- ♝ - ♙ - - - -
4- ♟ - - ♙ - - -
3- - ♘ - - ♕ - ♟
2♙ ♙ ♙ ♗ ♗ ♙ ♙ ♙
1♖ - - - ♔ - - ♖

2018/12/14 00:53:57 Got 42 nodes at depth 1
2018/12/14 00:53:57 Stockfish Got 41 nodes at depth 1
2018/12/14 00:53:57 FAIL
2018/12/14 00:53:57 INVALID MOVE e8g8
```
https://lichess.org/study/X2Z5X4XD
(Looks like castle flag didn't get cleared after nxh8)

```
2018/12/14 00:53:58 Testing rnbq1k1r/pp1Pbppp/2p5/8/2B5/8/PPP1NnPP/RNBQK2R w KQ - 1 8
2018/12/14 00:53:58
 A B C D E F G H
8♜ ♞ ♝ ♛ - ♚ - ♜
7♟ ♟ - ♙ ♝ ♟ ♟ ♟
6- - ♟ - - - - -
5- - - - - - - -
4- - ♗ - - - - -
3- - - - - - - -
2♙ ♙ ♙ - ♘ ♞ ♙ ♙
1♖ ♘ ♗ ♕ ♔ - - ♖

2018/12/14 00:54:01 Got 2104591 nodes at depth 4
2018/12/14 00:54:01 Stockfish Got 2103487 nodes at depth 4
2018/12/14 00:54:01 FAIL
2018/12/14 00:54:01 INVALID MOVE d7c8n
```

https://lichess.org/study/9P4L6Ubp

Same castling bug. Flags don't get cleared, and the generator seems to blindly trust flags.

**Comment by captncraig** [comment]
With the above bugfix, I have this package perfectly matching stockfish on all 7 starting positions through depth 4.

Running depth 5 now.

**Comment by captncraig** [comment]
Depth 5 passes as well.

**Comment by notnil** [comment]
@Kerrigan29a and @captncraig super impressed with methodology to hunt down this bug.  I'm sure I will be blindly accepting your PRs in the future :)

**Comment by Kerrigan29a** [comment]
@captncraig  I have added a basic cache mechanism and parallelization to perf tests in #27

**Pull request merged**
